# Autogenerated file. Do not modify
from __future__ import annotations

from .abstract import EiDatabase, EiDatabaseCustomType, EiDatabaseTable, EiDatabaseTableRow


class AcksUniqueType1(EiDatabaseCustomType):

    __slots__ = (
        "path",
        "unk2",
        "translate",
        "code",
    )

    def __init__(self):
        self.path: str | None = None
        self.unk2: int | None = None
        self.translate: str | None = None
        self.code: str | None = None
        super().__init__()


class AcksUniqueType2(EiDatabaseCustomType):

    __slots__ = (
        "path",
        "unk2",
        "translate",
        "code",
        "unk10",
    )

    def __init__(self):
        self.path: str | None = None
        self.unk2: int | None = None
        self.translate: str | None = None
        self.code: str | None = None
        self.unk10: int | None = None
        super().__init__()


class Answer(EiDatabaseTableRow):

    __slots__ = (
        "name",
        "select",
        "move",
        "attack",
        "cast",
        "loot",
        "useobj",
        "steal",
        "follow",
        "usepot",
        "chpos",
        "noway",
        "cntchpos",
        "nopath",
        "cantcast",
        "canttele",
        "skifail",
        "notarget",
        "complsp",
        "dectoatt",
        "outstam",
        "armcrip",
        "legcrip",
        "bored",
        "unknown",
        "overload",
        "injured",
        "bigatt",
        "armorcrip",
        "wearcrip",
        "attindef",
        "waitfoll",
        "scenario",
        "stealemp",
        "shopyes",
        "shopno",
    )

    def __init__(self):
        self.name: str | None = None
        self.select: list[AcksUniqueType1] | None = None
        self.move: list[AcksUniqueType1] | None = None
        self.attack: list[AcksUniqueType1] | None = None
        self.cast: list[AcksUniqueType1] | None = None
        self.loot: list[AcksUniqueType1] | None = None
        self.useobj: list[AcksUniqueType1] | None = None
        self.steal: list[AcksUniqueType1] | None = None
        self.follow: list[AcksUniqueType1] | None = None
        self.usepot: list[AcksUniqueType1] | None = None
        self.chpos: list[AcksUniqueType1] | None = None
        self.noway: list[AcksUniqueType1] | None = None
        self.cntchpos: list[AcksUniqueType1] | None = None
        self.nopath: list[AcksUniqueType1] | None = None
        self.cantcast: list[AcksUniqueType1] | None = None
        self.canttele: list[AcksUniqueType1] | None = None
        self.skifail: list[AcksUniqueType1] | None = None
        self.notarget: list[AcksUniqueType1] | None = None
        self.complsp: list[AcksUniqueType1] | None = None
        self.dectoatt: list[AcksUniqueType1] | None = None
        self.outstam: list[AcksUniqueType1] | None = None
        self.armcrip: list[AcksUniqueType1] | None = None
        self.legcrip: list[AcksUniqueType1] | None = None
        self.bored: list[AcksUniqueType2] | None = None
        self.unknown: list[AcksUniqueType1] | None = None
        self.overload: list[AcksUniqueType1] | None = None
        self.injured: list[AcksUniqueType1] | None = None
        self.bigatt: list[AcksUniqueType1] | None = None
        self.armorcrip: list[AcksUniqueType1] | None = None
        self.wearcrip: list[AcksUniqueType1] | None = None
        self.attindef: list[AcksUniqueType1] | None = None
        self.waitfoll: list[AcksUniqueType1] | None = None
        self.scenario: list[AcksUniqueType1] | None = None
        self.stealemp: list[AcksUniqueType1] | None = None
        self.shopyes: list[AcksUniqueType1] | None = None
        self.shopno: list[AcksUniqueType1] | None = None
        super().__init__()

    @property
    def _db_type(self):
        return AcksDatabase


class Crye(EiDatabaseTableRow):

    __slots__ = (
        "name",
        "agress",
        "suspect",
        "kill",
        "rest",
        "inagress",
    )

    def __init__(self):
        self.name: str | None = None
        self.agress: list[AcksUniqueType1] | None = None
        self.suspect: list[AcksUniqueType1] | None = None
        self.kill: list[AcksUniqueType1] | None = None
        self.rest: list[AcksUniqueType1] | None = None
        self.inagress: list[AcksUniqueType1] | None = None
        super().__init__()

    @property
    def _db_type(self):
        return AcksDatabase


class Other(EiDatabaseTableRow):

    __slots__ = (
        "name",
        "talk",
        "rest",
    )

    def __init__(self):
        self.name: str | None = None
        self.talk: list[AcksUniqueType1] | None = None
        self.rest: list[AcksUniqueType1] | None = None
        super().__init__()

    @property
    def _db_type(self):
        return AcksDatabase


class Answers(EiDatabaseTable[Answer]):

    _row_type = Answer


class Cryes(EiDatabaseTable[Crye]):

    _row_type = Crye


class Others(EiDatabaseTable[Other]):

    _row_type = Other


class AcksDatabase(EiDatabase):

    __slots__ = (
        "answers",
        "cryes",
        "others",
    )
    _custom_types = {t.__name__: t for t in (AcksUniqueType1, AcksUniqueType2,)}

    def __init__(self):
        self.answers = Answers()
        self.cryes = Cryes()
        self.others = Others()
        super().__init__()
