# Autogenerated file. Do not modify
from __future__ import annotations

from .abstract import EiDatabase, EiDatabaseTable, EiDatabaseTableRow


class Skill(EiDatabaseTableRow):

    __slots__ = (
        "name",
        "code",
        "texture_type_index",
        "base_attributes",
    )

    def __init__(self):
        self.name: str | None = None
        self.code: str | None = None
        self.texture_type_index: int | None = None
        self.base_attributes: list[str] | None = None
        super().__init__()

    @property
    def _db_type(self):
        return PerksDatabase


class Perk(EiDatabaseTableRow):

    __slots__ = (
        "name",
        "code",
        "texture_type_index",
        "perk",
        "skill",
        "skillid",
        "unk13",
        "skill_level",
        "strength",
        "dexterity",
        "intelligence",
        "cost",
        "modifier",
        "mult",
        "add",
        "active",
        "perk_exclusive",
    )

    def __init__(self):
        self.name: str | None = None
        self.code: str | None = None
        self.texture_type_index: int | None = None
        self.perk: str | None = None
        self.skill: str | None = None
        self.skillid: int | None = None
        self.unk13: int | None = None
        self.skill_level: int | None = None
        self.strength: float | None = None
        self.dexterity: float | None = None
        self.intelligence: float | None = None
        self.cost: int | None = None
        self.modifier: int | None = None
        self.mult: int | None = None
        self.add: int | None = None
        self.active: int | None = None
        self.perk_exclusive: int | None = None
        super().__init__()

    @property
    def _db_type(self):
        return PerksDatabase


class Skills(EiDatabaseTable[Skill]):

    _row_type = Skill


class Perks(EiDatabaseTable[Perk]):

    _row_type = Perk


class PerksDatabase(EiDatabase):

    __slots__ = (
        "skills",
        "perks",
    )

    def __init__(self):
        self.skills = Skills()
        self.perks = Perks()
        super().__init__()
