# Autogenerated file. Do not modify
from __future__ import annotations

from .abstract import EiDatabase, EiDatabaseTable, EiDatabaseTableRow


class Quest(EiDatabaseTableRow):

    __slots__ = (
        "name",
        "experience",
        "unk2",
        "zone_number",
        "comment",
        "money",
        "record_number",
        "unk7",
    )

    def __init__(self):
        self.name: str | None = None
        self.experience: float | None = None
        self.unk2: int | None = None
        self.zone_number: int | None = None
        self.comment: str | None = None
        self.money: int | None = None
        self.record_number: int | None = None
        self.unk7: list[str] | None = None
        super().__init__()

    @property
    def _db_type(self):
        return QuestsDatabase


class Briefing(EiDatabaseTableRow):

    __slots__ = (
        "name",
        "unk1",
        "money",
        "give_items",
        "comment",
        "take_items",
        "give_quests_1",
        "give_quests_2",
        "open_zones",
        "unk9",
        "bonus_number",
    )

    def __init__(self):
        self.name: str | None = None
        self.unk1: float | None = None
        self.money: float | None = None
        self.give_items: list[str] | None = None
        self.comment: str | None = None
        self.take_items: list[str] | None = None
        self.give_quests_1: list[str] | None = None
        self.give_quests_2: list[str] | None = None
        self.open_zones: list[str] | None = None
        self.unk9: list[str] | None = None
        self.bonus_number: int | None = None
        super().__init__()

    @property
    def _db_type(self):
        return QuestsDatabase


class Quests(EiDatabaseTable[Quest]):

    _row_type = Quest


class Briefings(EiDatabaseTable[Briefing]):

    _row_type = Briefing


class QuestsDatabase(EiDatabase):

    __slots__ = (
        "quests",
        "briefings",
    )

    def __init__(self):
        self.quests = Quests()
        self.briefings = Briefings()
        super().__init__()
